USE [master]
GO
/****** Object:  Database [Doomsday]    Script Date: 12/8/2022 4:03:51 PM ******/
CREATE DATABASE [Doomsday]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Doomsday', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\Doomsday.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Doomsday_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\Doomsday_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [Doomsday] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Doomsday].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [Doomsday] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [Doomsday] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [Doomsday] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [Doomsday] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [Doomsday] SET ARITHABORT OFF 
GO
ALTER DATABASE [Doomsday] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [Doomsday] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [Doomsday] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [Doomsday] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [Doomsday] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [Doomsday] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [Doomsday] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [Doomsday] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [Doomsday] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [Doomsday] SET  ENABLE_BROKER 
GO
ALTER DATABASE [Doomsday] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [Doomsday] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [Doomsday] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [Doomsday] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [Doomsday] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [Doomsday] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [Doomsday] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [Doomsday] SET RECOVERY FULL 
GO
ALTER DATABASE [Doomsday] SET  MULTI_USER 
GO
ALTER DATABASE [Doomsday] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [Doomsday] SET DB_CHAINING OFF 
GO
ALTER DATABASE [Doomsday] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [Doomsday] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [Doomsday] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [Doomsday] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
EXEC sys.sp_db_vardecimal_storage_format N'Doomsday', N'ON'
GO
ALTER DATABASE [Doomsday] SET QUERY_STORE = OFF
GO
USE [Doomsday]
GO
/****** Object:  Table [dbo].[Ammo]    Script Date: 12/8/2022 4:03:52 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Ammo](
	[AmmoID] [char](4) NOT NULL,
	[AmmoName] [varchar](50) NOT NULL,
 CONSTRAINT [PK_AmmoID] PRIMARY KEY CLUSTERED 
(
	[AmmoID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[AmmoInventory]    Script Date: 12/8/2022 4:03:52 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[AmmoInventory](
	[CampID] [char](4) NOT NULL,
	[AmmoID] [char](4) NOT NULL,
	[InventoryID] [char](4) NOT NULL,
	[AmmoInventoryQuantity] [smallint] NOT NULL,
 CONSTRAINT [PK_AmmoInventory] PRIMARY KEY CLUSTERED 
(
	[CampID] ASC,
	[AmmoID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Camps]    Script Date: 12/8/2022 4:03:52 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Camps](
	[CampID] [char](4) NOT NULL,
	[CampLocation] [varchar](50) NOT NULL,
	[PowerSourceID] [char](5) NOT NULL,
	[CampPowerConsumption] [varchar](50) NOT NULL,
 CONSTRAINT [PK_CampID] PRIMARY KEY CLUSTERED 
(
	[CampID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Groups]    Script Date: 12/8/2022 4:03:52 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Groups](
	[GroupID] [char](4) NOT NULL,
	[GroupName] [varchar](50) NOT NULL,
	[GroupTypeID] [char](5) NOT NULL,
	[GroupLeader] [varchar](50) NOT NULL,
	[GroupDescription] [varchar](50) NOT NULL,
 CONSTRAINT [PK_GroupID] PRIMARY KEY CLUSTERED 
(
	[GroupID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[GroupType]    Script Date: 12/8/2022 4:03:52 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[GroupType](
	[GroupTypeID] [char](5) NOT NULL,
	[GroupType] [varchar](50) NOT NULL,
 CONSTRAINT [PK_GroupTypeID] PRIMARY KEY CLUSTERED 
(
	[GroupTypeID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Inventory]    Script Date: 12/8/2022 4:03:52 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Inventory](
	[InventoryID] [char](4) NOT NULL,
	[CampID] [char](4) NOT NULL,
	[InventoryTypeID] [char](5) NOT NULL,
	[InventoryQuantity] [smallint] NOT NULL,
 CONSTRAINT [PK_InventoryID] PRIMARY KEY CLUSTERED 
(
	[InventoryID] ASC,
	[CampID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[InventoryInfo]    Script Date: 12/8/2022 4:03:52 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[InventoryInfo](
	[InventoryID] [char](4) NOT NULL,
	[InventoryName] [varchar](50) NOT NULL,
	[InventoryUnit] [varchar](50) NOT NULL,
 CONSTRAINT [PK_InventoryInfo] PRIMARY KEY CLUSTERED 
(
	[InventoryID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[InventoryType]    Script Date: 12/8/2022 4:03:52 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[InventoryType](
	[InventoryTypeID] [char](5) NOT NULL,
	[InventoryType] [varchar](50) NOT NULL,
 CONSTRAINT [PK_InventoryTypeID] PRIMARY KEY CLUSTERED 
(
	[InventoryTypeID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Jobs]    Script Date: 12/8/2022 4:03:52 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Jobs](
	[JobID] [char](4) NOT NULL,
	[JobType] [varchar](50) NOT NULL,
	[JobSalary] [int] NOT NULL,
 CONSTRAINT [PK_JobsID] PRIMARY KEY CLUSTERED 
(
	[JobID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[People]    Script Date: 12/8/2022 4:03:52 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[People](
	[PeopleID] [char](4) NOT NULL,
	[PeopleFirstName] [varchar](50) NOT NULL,
	[PeopleLastName] [varchar](50) NOT NULL,
	[PeopleBirthDate] [date] NOT NULL,
	[PeopleJoinDate] [date] NOT NULL,
	[PeopleGender] [char](1) NOT NULL,
	[PeopleHealth] [tinyint] NOT NULL,
 CONSTRAINT [PK_PeopleID] PRIMARY KEY CLUSTERED 
(
	[PeopleID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[PeopleInfo]    Script Date: 12/8/2022 4:03:52 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PeopleInfo](
	[PeopleID] [char](4) NOT NULL,
	[JobID] [char](4) NULL,
	[CampID] [char](4) NOT NULL,
 CONSTRAINT [PK_PeopleInfoID] PRIMARY KEY CLUSTERED 
(
	[PeopleID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[PeopleSkills]    Script Date: 12/8/2022 4:03:52 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PeopleSkills](
	[PeopleID] [char](4) NOT NULL,
	[SkillID] [char](5) NOT NULL,
 CONSTRAINT [PK_PeopleSkillsID] PRIMARY KEY CLUSTERED 
(
	[PeopleID] ASC,
	[SkillID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[PowerSource]    Script Date: 12/8/2022 4:03:52 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PowerSource](
	[PowerSourceID] [char](5) NOT NULL,
	[PowerSourceDescription] [varchar](50) NOT NULL,
	[PowerSourceProduction] [int] NOT NULL,
 CONSTRAINT [PK_PowerSourceID] PRIMARY KEY CLUSTERED 
(
	[PowerSourceID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Skills]    Script Date: 12/8/2022 4:03:52 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Skills](
	[SkillID] [char](5) NOT NULL,
	[Skill] [varchar](50) NOT NULL,
	[SkillDescription] [varchar](100) NOT NULL,
 CONSTRAINT [PK_SkillsID] PRIMARY KEY CLUSTERED 
(
	[SkillID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[AmmoInventory]  WITH CHECK ADD  CONSTRAINT [FK_AmmoID] FOREIGN KEY([AmmoID])
REFERENCES [dbo].[Ammo] ([AmmoID])
GO
ALTER TABLE [dbo].[AmmoInventory] CHECK CONSTRAINT [FK_AmmoID]
GO
ALTER TABLE [dbo].[AmmoInventory]  WITH CHECK ADD  CONSTRAINT [FK_AmmoInventoryCamp] FOREIGN KEY([CampID])
REFERENCES [dbo].[Camps] ([CampID])
GO
ALTER TABLE [dbo].[AmmoInventory] CHECK CONSTRAINT [FK_AmmoInventoryCamp]
GO
ALTER TABLE [dbo].[AmmoInventory]  WITH CHECK ADD  CONSTRAINT [FK_InventoryID] FOREIGN KEY([InventoryID])
REFERENCES [dbo].[InventoryInfo] ([InventoryID])
GO
ALTER TABLE [dbo].[AmmoInventory] CHECK CONSTRAINT [FK_InventoryID]
GO
ALTER TABLE [dbo].[Camps]  WITH CHECK ADD  CONSTRAINT [FK_PowerSourceID] FOREIGN KEY([PowerSourceID])
REFERENCES [dbo].[PowerSource] ([PowerSourceID])
GO
ALTER TABLE [dbo].[Camps] CHECK CONSTRAINT [FK_PowerSourceID]
GO
ALTER TABLE [dbo].[Inventory]  WITH CHECK ADD  CONSTRAINT [FK_CampID] FOREIGN KEY([CampID])
REFERENCES [dbo].[Camps] ([CampID])
GO
ALTER TABLE [dbo].[Inventory] CHECK CONSTRAINT [FK_CampID]
GO
ALTER TABLE [dbo].[Inventory]  WITH CHECK ADD  CONSTRAINT [FK_CampInventory] FOREIGN KEY([InventoryID])
REFERENCES [dbo].[InventoryInfo] ([InventoryID])
GO
ALTER TABLE [dbo].[Inventory] CHECK CONSTRAINT [FK_CampInventory]
GO
ALTER TABLE [dbo].[Inventory]  WITH CHECK ADD  CONSTRAINT [FK_InventoryTypeID] FOREIGN KEY([InventoryTypeID])
REFERENCES [dbo].[InventoryType] ([InventoryTypeID])
GO
ALTER TABLE [dbo].[Inventory] CHECK CONSTRAINT [FK_InventoryTypeID]
GO
ALTER TABLE [dbo].[PeopleInfo]  WITH CHECK ADD  CONSTRAINT [FK_JobID] FOREIGN KEY([JobID])
REFERENCES [dbo].[Jobs] ([JobID])
GO
ALTER TABLE [dbo].[PeopleInfo] CHECK CONSTRAINT [FK_JobID]
GO
ALTER TABLE [dbo].[PeopleInfo]  WITH CHECK ADD  CONSTRAINT [FK_PeopleInfoCamp] FOREIGN KEY([CampID])
REFERENCES [dbo].[Camps] ([CampID])
GO
ALTER TABLE [dbo].[PeopleInfo] CHECK CONSTRAINT [FK_PeopleInfoCamp]
GO
ALTER TABLE [dbo].[PeopleSkills]  WITH CHECK ADD  CONSTRAINT [FK_PeopleID] FOREIGN KEY([PeopleID])
REFERENCES [dbo].[People] ([PeopleID])
GO
ALTER TABLE [dbo].[PeopleSkills] CHECK CONSTRAINT [FK_PeopleID]
GO
ALTER TABLE [dbo].[PeopleSkills]  WITH CHECK ADD  CONSTRAINT [FK_SkillID] FOREIGN KEY([SkillID])
REFERENCES [dbo].[Skills] ([SkillID])
GO
ALTER TABLE [dbo].[PeopleSkills] CHECK CONSTRAINT [FK_SkillID]
GO
ALTER TABLE [dbo].[Ammo]  WITH CHECK ADD  CONSTRAINT [CHECK_AMMO_KEY] CHECK  (([AmmoID] like 'A[0-9][0-9][0-9]'))
GO
ALTER TABLE [dbo].[Ammo] CHECK CONSTRAINT [CHECK_AMMO_KEY]
GO
ALTER TABLE [dbo].[AmmoInventory]  WITH CHECK ADD  CONSTRAINT [CHECK_AMMO_INVENTORY_QTY] CHECK  (([AmmoInventoryQuantity]>=(0)))
GO
ALTER TABLE [dbo].[AmmoInventory] CHECK CONSTRAINT [CHECK_AMMO_INVENTORY_QTY]
GO
ALTER TABLE [dbo].[Camps]  WITH CHECK ADD  CONSTRAINT [CHECK_CAMP_KEY] CHECK  (([CampID] like 'C[0-9][0-9][0-9]'))
GO
ALTER TABLE [dbo].[Camps] CHECK CONSTRAINT [CHECK_CAMP_KEY]
GO
ALTER TABLE [dbo].[Camps]  WITH CHECK ADD  CONSTRAINT [CHECK_POWER_CON] CHECK  (([CampPowerConsumption]>=(0)))
GO
ALTER TABLE [dbo].[Camps] CHECK CONSTRAINT [CHECK_POWER_CON]
GO
ALTER TABLE [dbo].[Groups]  WITH CHECK ADD  CONSTRAINT [CHECK_GROUPS_KEY] CHECK  (([GroupID] like 'G[0-9][0-9][0-9]'))
GO
ALTER TABLE [dbo].[Groups] CHECK CONSTRAINT [CHECK_GROUPS_KEY]
GO
ALTER TABLE [dbo].[GroupType]  WITH CHECK ADD  CONSTRAINT [CHECK_GROUP_TYPE_KEY] CHECK  (([GroupTypeID] like 'GT[0-9][0-9][0-9]'))
GO
ALTER TABLE [dbo].[GroupType] CHECK CONSTRAINT [CHECK_GROUP_TYPE_KEY]
GO
ALTER TABLE [dbo].[Inventory]  WITH CHECK ADD  CONSTRAINT [CHECK_INVENTORY_QTY] CHECK  (([InventoryQuantity]>=(0)))
GO
ALTER TABLE [dbo].[Inventory] CHECK CONSTRAINT [CHECK_INVENTORY_QTY]
GO
ALTER TABLE [dbo].[InventoryInfo]  WITH CHECK ADD  CONSTRAINT [CHECK_INVENTORY_KEY] CHECK  (([InventoryID] like 'I[0-9][0-9][0-9]'))
GO
ALTER TABLE [dbo].[InventoryInfo] CHECK CONSTRAINT [CHECK_INVENTORY_KEY]
GO
ALTER TABLE [dbo].[InventoryType]  WITH CHECK ADD  CONSTRAINT [CHECK_INVENTORY_TYPE_KEY] CHECK  (([InventoryTypeID] like 'IT[0-9][0-9][0-9]'))
GO
ALTER TABLE [dbo].[InventoryType] CHECK CONSTRAINT [CHECK_INVENTORY_TYPE_KEY]
GO
ALTER TABLE [dbo].[Jobs]  WITH CHECK ADD  CONSTRAINT [CHECK_JOBS_KEY] CHECK  (([JobID] like 'J[0-9][0-9][0-9]'))
GO
ALTER TABLE [dbo].[Jobs] CHECK CONSTRAINT [CHECK_JOBS_KEY]
GO
ALTER TABLE [dbo].[Jobs]  WITH CHECK ADD  CONSTRAINT [CHECK_SALARY] CHECK  (([JobSalary]>=(0)))
GO
ALTER TABLE [dbo].[Jobs] CHECK CONSTRAINT [CHECK_SALARY]
GO
ALTER TABLE [dbo].[People]  WITH CHECK ADD  CONSTRAINT [CHECK_HEALTH] CHECK  (([PeopleHealth]>=(1) AND [PeopleHealth]<=(5)))
GO
ALTER TABLE [dbo].[People] CHECK CONSTRAINT [CHECK_HEALTH]
GO
ALTER TABLE [dbo].[People]  WITH CHECK ADD  CONSTRAINT [CHECK_PEOPLE_KEY] CHECK  (([PeopleID] like 'P[0-9][0-9][0-9]'))
GO
ALTER TABLE [dbo].[People] CHECK CONSTRAINT [CHECK_PEOPLE_KEY]
GO
ALTER TABLE [dbo].[PowerSource]  WITH CHECK ADD  CONSTRAINT [CHECK_POWER_PRO] CHECK  (([PowerSourceProduction]>=(0)))
GO
ALTER TABLE [dbo].[PowerSource] CHECK CONSTRAINT [CHECK_POWER_PRO]
GO
ALTER TABLE [dbo].[PowerSource]  WITH CHECK ADD  CONSTRAINT [CHECK_PWR_KEY] CHECK  (([PowerSourceID] like 'PS[0-9][0-9][0-9]'))
GO
ALTER TABLE [dbo].[PowerSource] CHECK CONSTRAINT [CHECK_PWR_KEY]
GO
ALTER TABLE [dbo].[Skills]  WITH CHECK ADD  CONSTRAINT [CHECK_SKILLS_KEY] CHECK  (([SkillID] like 'SK[0-9][0-9][0-9]'))
GO
ALTER TABLE [dbo].[Skills] CHECK CONSTRAINT [CHECK_SKILLS_KEY]
GO
USE [master]
GO
ALTER DATABASE [Doomsday] SET  READ_WRITE 
GO
